### ISSUE TITLE
The navbar is not green enough.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/greenhat.today#1]
![image](https://user-images.githubusercontent.com/19531547/133376877-c9bb8026-5691-4076-8d77-50b15c6a52c9.png)

You should use:

```css
.bg-success {
    background-color: green!important;
}
```

To make it more green!
